// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/internal/v1/user": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用戶"
                ],
                "summary": "新增",
                "parameters": [
                    {
                        "description": "會員資料",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/internal/v1/user/{id}": {
            "delete": {
                "description": "說明",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用戶"
                ],
                "summary": "刪除",
                "responses": {}
            },
            "patch": {
                "description": "說明",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用戶"
                ],
                "summary": "部份更新",
                "responses": {}
            }
        },
        "/private/v1/user/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用戶"
                ],
                "summary": "查單筆",
                "parameters": [
                    {
                        "type": "string",
                        "description": "會員id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用戶"
                ],
                "summary": "查多筆",
                "parameters": [
                    {
                        "type": "string",
                        "description": "會員姓名",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "A",
                            "B",
                            "C"
                        ],
                        "type": "string",
                        "description": "職級",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "CreditCard",
                                "LinePay",
                                "ApplePay"
                            ],
                            "type": "string"
                        },
                        "description": "支付方式",
                        "name": "method",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "model.User": {
            "type": "object",
            "properties": {
                "level": {
                    "description": "職級",
                    "type": "string",
                    "example": "A"
                },
                "method": {
                    "description": "支付方式",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ApplePay"
                    ]
                },
                "name": {
                    "description": "姓名",
                    "type": "string",
                    "example": "david"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
